// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4zubU_gjYgW38VCcuCXdWbQNQyzt7xUI',
    appId: '1:348336214539:web:a430a1e5d51e60aeeead0e',
    messagingSenderId: '348336214539',
    projectId: 'fir-auth-68c40',
    authDomain: 'fir-auth-68c40.firebaseapp.com',
    storageBucket: 'fir-auth-68c40.appspot.com',
    measurementId: 'G-6NNCLMTW3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWdDto_HyLW2tbuYEvpu13sSZoLoXAP5s',
    appId: '1:348336214539:android:d0b55cfeac8e90e9eead0e',
    messagingSenderId: '348336214539',
    projectId: 'fir-auth-68c40',
    storageBucket: 'fir-auth-68c40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKQGJAMIFA1FI1zeY64l38v9qHhIJFFUs',
    appId: '1:348336214539:ios:7b43179cd23d4a58eead0e',
    messagingSenderId: '348336214539',
    projectId: 'fir-auth-68c40',
    storageBucket: 'fir-auth-68c40.appspot.com',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKQGJAMIFA1FI1zeY64l38v9qHhIJFFUs',
    appId: '1:348336214539:ios:1bf9d97de3f57de2eead0e',
    messagingSenderId: '348336214539',
    projectId: 'fir-auth-68c40',
    storageBucket: 'fir-auth-68c40.appspot.com',
    iosBundleId: 'com.example.realestate.RunnerTests',
  );
}
